[repository]
name = "morebinds"
authors = ["rafay"]
commit-pins = [
    ["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "4dc7b6f2a9ad996aa67645923410a166c9d3c164"] # v0.41.1
]

[morebinds]
description = "a plugin that allows you to set binds for double tapping mod keys"
authors = ["rafay"]
output = "build/libmorebinds.so"
build = [
    "make -C build/"
]